"""
Portfolio Report Generator for Nifty 100 Financial Intelligence Platform.
Generates Portfolio Summary PDF combining investment intelligence in reports/portfolio/portfolio_summary_report.pdf.
"""

import os
import sqlite3
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

DB_PATH = os.getenv("DB_PATH", "nifty100.db")
OUTPUT_DIR = os.path.join("reports", "portfolio")
REPORT_PATH = os.path.join(OUTPUT_DIR, "portfolio_summary_report.pdf")


def generate_portfolio_report(db_path: str = DB_PATH, output_file: str = REPORT_PATH):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    conn = sqlite3.connect(db_path)

    sql = """
        SELECT ins.company_id as Ticker, c.company_name as Company, s.broad_sector as Sector,
               ins.investment_score as Score, ins.investment_rating as Rating,
               ins.quality_score as Quality, ins.growth_score as Growth, ins.value_score as Value
        FROM investment_scores ins
        JOIN companies c ON ins.company_id = c.id
        LEFT JOIN sectors s ON ins.company_id = s.company_id
        WHERE ins.investment_rating IN ('Strong Buy', 'Buy')
        ORDER BY ins.investment_score DESC
    """
    df = pd.read_sql_query(sql, conn)
    conn.close()

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('DocTitle', parent=styles['Heading1'], fontSize=18, textColor=colors.HexColor('#1F4E78'), spaceAfter=6)
    sub_style = ParagraphStyle('DocSubTitle', parent=styles['Heading3'], fontSize=11, textColor=colors.HexColor('#555555'), spaceAfter=12)
    h2_style = ParagraphStyle('SectionHeading', parent=styles['Heading2'], fontSize=12, textColor=colors.HexColor('#1F4E78'), spaceBefore=10, spaceAfter=6)

    doc = SimpleDocTemplate(output_file, pagesize=letter, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
    story = []

    story.append(Paragraph("Nifty 100 Investment Portfolio Summary", title_style))
    story.append(Paragraph("High-Conviction Investment Candidates (Strong Buy & Buy Ratings)", sub_style))

    story.append(Paragraph(f"Top Allocation Candidates ({len(df)} Companies)", h2_style))

    table_data = [["Ticker", "Company Name", "Sector", "Score", "Rating", "Quality", "Growth", "Value"]]
    for _, row in df.iterrows():
        table_data.append([
            row['Ticker'],
            row['Company'],
            str(row['Sector']) if pd.notna(row['Sector']) else "N/A",
            f"{row['Score']:.1f}",
            str(row['Rating']),
            f"{row['Quality']:.1f}",
            f"{row['Growth']:.1f}",
            f"{row['Value']:.1f}"
        ])

    t = Table(table_data, colWidths=[65, 170, 115, 45, 65, 45, 45, 45])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1F4E78')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CCCCCC')),
        ('PADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(t)

    story.append(Spacer(1, 20))
    story.append(Paragraph("Report Generated by Bluestock Fintech N100 Portfolio Intelligence Engine.", ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.gray)))

    doc.build(story)
    print(f"[INFO] Generated Portfolio Summary Report: {output_file}")


if __name__ == "__main__":
    generate_portfolio_report()
