"""
Sector Report Generator for Nifty 100 Financial Intelligence Platform.
Generates one PDF report for every broad sector in reports/sector/<SECTOR>_sector_report.pdf.
"""

import os
import sqlite3
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

DB_PATH = os.getenv("DB_PATH", "nifty100.db")
OUTPUT_DIR = os.path.join("reports", "sector")


def generate_sector_reports(db_path: str = DB_PATH, output_dir: str = OUTPUT_DIR) -> int:
    os.makedirs(output_dir, exist_ok=True)
    conn = sqlite3.connect(db_path)

    sec_df = pd.read_sql_query("SELECT DISTINCT broad_sector FROM sectors WHERE broad_sector IS NOT NULL", conn)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('DocTitle', parent=styles['Heading1'], fontSize=18, textColor=colors.HexColor('#1F4E78'), spaceAfter=6)
    sub_style = ParagraphStyle('DocSubTitle', parent=styles['Heading3'], fontSize=11, textColor=colors.HexColor('#555555'), spaceAfter=12)
    h2_style = ParagraphStyle('SectionHeading', parent=styles['Heading2'], fontSize=12, textColor=colors.HexColor('#1F4E78'), spaceBefore=10, spaceAfter=6)

    count = 0
    for _, sec in sec_df.iterrows():
        sector_name = sec["broad_sector"]
        clean_sec_name = sector_name.replace(" ", "_").replace("/", "_")

        sql = f"""
            SELECT c.id as Ticker, c.company_name as Company,
                   fr.return_on_equity_pct as ROE, fr.debt_to_equity as DE,
                   ins.investment_score as Score, ins.investment_rating as Rating
            FROM sectors s
            JOIN companies c ON s.company_id = c.id
            LEFT JOIN (
                SELECT fr_inner.* FROM financial_ratios fr_inner
                JOIN (SELECT company_id, MAX(year) as max_yr FROM financial_ratios WHERE year != 'PARSE_ERROR' GROUP BY company_id) latest
                ON fr_inner.company_id = latest.company_id AND fr_inner.year = latest.max_yr
            ) fr ON c.id = fr.company_id
            LEFT JOIN (
                SELECT ins_inner.* FROM investment_scores ins_inner
                JOIN (SELECT company_id, MAX(year) as max_yr FROM investment_scores GROUP BY company_id) latest
                ON ins_inner.company_id = latest.company_id AND ins_inner.year = latest.max_yr
            ) ins ON c.id = ins.company_id
            WHERE s.broad_sector = '{sector_name}'
            ORDER BY ins.investment_score DESC
        """
        cos_in_sec = pd.read_sql_query(sql, conn)

        pdf_path = os.path.join(output_dir, f"{clean_sec_name}_sector_report.pdf")
        doc = SimpleDocTemplate(pdf_path, pagesize=letter, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
        story = []

        story.append(Paragraph(f"Sector Intelligence Report: {sector_name}", title_style))
        story.append(Paragraph(f"Nifty 100 Broad Sector Analysis ({len(cos_in_sec)} Companies)", sub_style))

        story.append(Paragraph("Sector Constituent Overview & Ratings", h2_style))

        table_data = [["Ticker", "Company Name", "ROE %", "D/E", "Score", "Rating"]]
        for _, row in cos_in_sec.iterrows():
            roe_val = f"{row['ROE']:.1f}%" if pd.notna(row['ROE']) else "N/A"
            de_val = f"{row['DE']:.2f}" if pd.notna(row['DE']) else "N/A"
            score_val = f"{row['Score']:.1f}" if pd.notna(row['Score']) else "N/A"
            rating_val = str(row['Rating']) if pd.notna(row['Rating']) else "N/A"
            table_data.append([row['Ticker'], row['Company'], roe_val, de_val, score_val, rating_val])

        t = Table(table_data, colWidths=[70, 200, 60, 50, 60, 90])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1F4E78')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CCCCCC')),
            ('PADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(t)

        story.append(Spacer(1, 20))
        story.append(Paragraph("Report Generated by Bluestock Fintech N100 Sector Intelligence Engine.", ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.gray)))

        doc.build(story)
        count += 1

    conn.close()
    print(f"[INFO] Generated {count} sector PDF reports in {output_dir}.")
    return count


if __name__ == "__main__":
    generate_sector_reports()
